//! Roaming fauna on the planet surface and inside the maze venues.
//!
//! Roamers (deer, rabbit, fox, …) wander tile-to-tile within their home
//! terrains, pause to graze, and bolt when the player comes near — the mobile
//! evolution of the static `shy` peekers in `surface_objects`.  Fliers
//! (songbird, butterfly, drones) cruise over the map ignoring terrain and drop
//! a shadow on the ground below them.
//!
//! Everything shares the [`CharacterAnim`](crate::surface_character::CharacterAnim)
//! directional walk animation, driven by `LinearVelocity`, so these modules own
//! only the AI and the depth sorting:
//!
//! * [`spawn`] — keep a small off-screen-recycling population alive.
//! * [`behaviour`] — the graze / wander / flee / alert state machine.
//! * [`render`] — depth sorting and flier shadows.
//!
//! Art + per-species data come from `assets/sprites/fauna/fauna_manifest.ron`
//! (generated by `scripts/ship3d/fauna3d.py`).

use bevy::prelude::*;
use rand::SeedableRng;
use serde::Deserialize;

use crate::PlayState;
use crate::surface::TILE_PX;
use crate::surface_pathfinding::SurfaceCostMap;

mod behaviour;
mod render;
mod spawn;

pub use behaviour::run_fauna;
pub use render::depth_sort_fauna;
pub use spawn::spawn_fauna;

// ── Tuning ────────────────────────────────────────────────────────────────

/// How many roamers to keep alive on the surface at once.
const TARGET_FAUNA_COUNT: usize = 6;
/// Player distance (px) at which a roamer bolts.
const FLEE_RADIUS: f32 = 130.0;
/// A watching roamer bolts again if the player closes back inside this.
const RESPOOK_RADIUS: f32 = 170.0;
/// Beyond this the player is no longer worth watching and the roamer settles.
const CALM_DIST: f32 = 260.0;
/// Roamers this far from the player despawn (recycled off-screen).
const DESPAWN_DIST: f32 = 1500.0;
/// New roamers spawn this far from the player (off-screen) … but no further.
const SPAWN_MIN_DIST: f32 = 520.0;
const SPAWN_MAX_DIST: f32 = 1250.0;
/// Wander target is within this many tiles of the current position.
const WANDER_TILES: i32 = 5;
/// World distance (px) below which a roamer counts as "arrived" at its target.
const ARRIVE_DIST: f32 = 5.0;
/// Herd species bias their wander search this fraction of the way toward the
/// flock centroid, so they regroup and drift together (0 = none, 1 = at centroid).
const HERD_BIAS: f32 = 0.5;

/// Fliers cruise this far above their ground track (screen px) and sort over
/// everything; the bob is added on top so they never look pinned to a plane.
/// Indoors is much lower: a shop is one room, and a drone hanging a full
/// open-sky altitude above the floor would float well clear of the walls.
const FLY_ALTITUDE: f32 = 64.0;
const FLY_ALTITUDE_INSIDE: f32 = 26.0;
const FLY_BOB_PX: f32 = 7.0;
const FLY_Z: f32 = 8.0;

/// Width in px of `flier_shadow.png`, as written by `fauna3d.py`.
const SHADOW_PX: f32 = 48.0;

// ── RON manifest ─────────────────────────────────────────────────────────

#[derive(Deserialize, Debug)]
struct FaunaManifest {
    species: Vec<FaunaSpeciesDef>,
}

#[derive(Deserialize, Debug)]
struct FaunaSpeciesDef {
    name: String,
    sheet: String,
    biome: String,
    terrains: Vec<String>,
    tile_w: u32,
    tile_h: u32,
    speed: f32,
    flee_speed: f32,
    group: u32,
    flier: bool,
}

// ── Resources ──────────────────────────────────────────────────────────────

/// A spawnable species resolved for the current surface's biome.
struct FaunaSpecies {
    /// Manifest key ("deer", "mine_rat", …) — lets the ambience director
    /// pick a call sound for a spawned critter.
    key: String,
    image: Handle<Image>,
    layout: Handle<TextureAtlasLayout>,
    /// Home-terrain indices into the current biome's terrain table.
    terrain_idxs: Vec<u32>,
    speed: f32,
    flee_speed: f32,
    group: u32,
    foot_off: f32,
    /// Sprite scale for this species' ground shadow (fliers only).
    shadow_scale: f32,
    flier: bool,
}

/// The terrain grid plus the "can this species live here?" test.  Wrapping the
/// grid saves every caller from passing `(terrain, map_w, map_h)` around as
/// three loose arguments.
struct HomeGrid {
    terrain: Vec<u32>,
    w: u32,
    h: u32,
}

impl HomeGrid {
    /// Is tile (tx, ty) inside the map and one of `idxs`?
    fn is_home(&self, idxs: &[u32], tx: i32, ty: i32) -> bool {
        if tx < 0 || ty < 0 || tx as u32 >= self.w || ty as u32 >= self.h {
            return false;
        }
        idxs.contains(&self.terrain[(ty as u32 * self.w + tx as u32) as usize])
    }

    /// The same test for a world-space point.
    fn is_home_at(&self, idxs: &[u32], p: Vec2) -> bool {
        let (tx, ty) = tile_of(p);
        self.is_home(idxs, tx, ty)
    }

    /// Half the map's world-space size, for keeping fliers in bounds.
    fn half_extent(&self) -> Vec2 {
        Vec2::new(
            self.w as f32 * TILE_PX * 0.5 - TILE_PX,
            self.h as f32 * TILE_PX * 0.5 - TILE_PX,
        )
    }
}

/// Loaded fauna data + the live terrain grid, for the spawn/AI systems.
/// Only the species matching the surface's biome are kept.
#[derive(Resource)]
pub struct FaunaWorld {
    species: Vec<FaunaSpecies>,
    grid: HomeGrid,
    /// Blob sprite dropped on the ground under a flier.
    shadow: Handle<Image>,
    rng: rand::rngs::StdRng,
    spawn_timer: Timer,
    /// Which on-foot state owns the critters (surface or interior).
    scope: PlayState,
}

impl FaunaWorld {
    /// Manifest key for a critter's species index (see [`Fauna::species_idx`]).
    pub fn species_key(&self, idx: usize) -> Option<&str> {
        self.species.get(idx).map(|s| s.key.as_str())
    }
}

// ── Component ──────────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Debug)]
enum FaunaState {
    /// Head down feeding.  Breaks into short shuffling steps rather than
    /// standing perfectly still, which reads as a statue.
    Graze,
    /// Walking to `target`.
    Wander,
    /// Bolting away from the player.  Deliberately a short burst — an animal
    /// that sprints in a dead-straight line until it is 300px clear looks like
    /// it is on rails.  This ends in `Alert`, not in `Graze`.
    Flee,
    /// Stopped, facing the player, deciding.  Bolts again if he closes;
    /// settles back to grazing if he keeps his distance.
    Alert,
}

#[derive(Component)]
pub struct Fauna {
    species: usize,
    speed: f32,
    flee_speed: f32,
    foot_off: f32,
    state: FaunaState,
    timer: Timer,
    target: Vec2,
    flier: bool,
    /// Unit heading.  Held across frames so a bolt (or a flier's cruise) is a
    /// steady line the animal steers, not a fresh random draw every tick.
    heading: Vec2,
    /// Fliers: how far above the ground track this one cruises, in screen px.
    /// Fixed per critter (set from the scope at spawn) — the bob rides on the
    /// velocity instead, because avian owns the transform.
    altitude: f32,
    /// Fliers: current turn rate (rad/s), carried between frames.  A fresh
    /// random turn each tick averages out to a straight line; letting it decay
    /// toward a new value gives the lazy arcs that read as flight.
    turn: f32,
    /// Fliers: bob/flap phase, advanced by `run_fauna`.
    phase: f32,
}

impl Fauna {
    /// Index into [`FaunaWorld`]'s species table.
    pub fn species_idx(&self) -> usize {
        self.species
    }
}

/// A flier's ground shadow.  Spawned as a CHILD of the flier so it inherits the
/// horizontal track for free and dies with it; [`depth_sort_fauna`] then drops
/// it by the flier's altitude and sorts it with the ground.
#[derive(Component)]
pub struct FlierShadow;

// ── Setup / teardown (called from surface.rs) ───────────────────────────────

/// Load the fauna manifest, resolve the species that belong to `biome_name`,
/// and insert [`FaunaWorld`].  Call from `setup_surface`.
#[allow(clippy::too_many_arguments)]
pub fn setup_fauna(
    commands: &mut Commands,
    asset_server: &AssetServer,
    atlas_layouts: &mut Assets<TextureAtlasLayout>,
    terrain_flat: &[u32],
    terrain_names: &[String],
    biome_name: &str,
    map_w: u32,
    map_h: u32,
    seed: u64,
    scope: PlayState,
) {
    let manifest: FaunaManifest =
        match crate::embedded_assets::read_to_string("assets/sprites/fauna/fauna_manifest.ron")
            .ok()
            .and_then(|t| ron::from_str(&t).ok())
        {
            Some(m) => m,
            None => {
                eprintln!("[fauna] WARNING: could not load fauna_manifest.ron");
                return;
            }
        };

    let idx_by_name: std::collections::HashMap<&str, u32> = terrain_names
        .iter()
        .enumerate()
        .map(|(i, n)| (n.as_str(), i as u32))
        .collect();

    let mut species = Vec::new();
    for def in &manifest.species {
        if def.biome != biome_name {
            continue;
        }
        let terrain_idxs: Vec<u32> = def
            .terrains
            .iter()
            .filter_map(|t| idx_by_name.get(t.as_str()).copied())
            .collect();
        if terrain_idxs.is_empty() {
            continue;
        }
        let layout = atlas_layouts.add(TextureAtlasLayout::from_grid(
            UVec2::new(def.tile_w, def.tile_h),
            3, // still, w1, w2
            4, // down, left, right, up
            None,
            None,
        ));
        species.push(FaunaSpecies {
            key: def.name.clone(),
            image: asset_server.load(def.sheet.clone()),
            layout,
            terrain_idxs,
            speed: def.speed,
            flee_speed: def.flee_speed,
            group: def.group.max(1),
            foot_off: def.tile_h as f32 * 0.35,
            shadow_scale: def.tile_w as f32 * 0.62 / SHADOW_PX,
            flier: def.flier,
        });
    }

    if species.is_empty() {
        return; // this biome has no roamers yet
    }

    commands.insert_resource(FaunaWorld {
        species,
        grid: HomeGrid {
            terrain: terrain_flat.to_vec(),
            w: map_w,
            h: map_h,
        },
        shadow: asset_server.load("sprites/fauna/flier_shadow.png"),
        rng: rand::rngs::StdRng::seed_from_u64(seed.wrapping_add(0xFA00_0001)),
        spawn_timer: Timer::from_seconds(1.5, TimerMode::Repeating),
        scope,
    });
}

pub fn cleanup_fauna(mut commands: Commands) {
    commands.remove_resource::<FaunaWorld>();
}

fn tile_of(pos: Vec2) -> (i32, i32) {
    let (tx, ty) = SurfaceCostMap::world_to_tile(pos);
    (tx as i32, ty as i32)
}
