name: avian-sprites
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - tbparse
  - pip:
      - Pillow==11.3.0
      - PyYAML>=6.0
      - trimesh>=4.0
      - pyrender>=0.1.45
      - noise>=1.2.2
