#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""
weapons_overview.py — regenerate docs/weapons_overview.md from the asset files.

Reads assets/weapons.yaml (damage, cooldown, speed, lifetime, guided, ammo) and
assets/outfitter_items.yaml (space, price, required_unlocks) and writes a reference
doc with the derived combat metrics:

  * DPS            = damage / cooldown      (per mounted copy; N copies fire at
                     rate N/cooldown, so total DPS = N * damage / cooldown)
  * DPS per space  = DPS / item-space       (efficiency: damage-per-second per
                     unit of item space the weapon occupies)
  * range          = speed * lifetime       (projectile despawns after `lifetime`s;
                     guided missiles cruise at `speed`)

Run:  uv run scripts/weapons_overview.py
"""
import os

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A = os.path.join(ROOT, "assets")


class Loader(yaml.SafeLoader):
    pass


def _tagged(loader, tag_suffix, node):
    val = (
        loader.construct_mapping(node, deep=True)
        if isinstance(node, yaml.MappingNode)
        else None
    )
    if isinstance(val, dict):
        val["__tag__"] = tag_suffix
    return val


Loader.add_multi_constructor("!", _tagged)


def load(name):
    with open(os.path.join(A, name)) as f:
        return yaml.load(f, Loader=Loader) or {}


def main():
    weapons = load("weapons.yaml")
    outfitter = load("outfitter_items.yaml")

    rows = []
    for wid, w in weapons.items():
        if not isinstance(w, dict):
            continue
        item = outfitter.get(wid)
        if not isinstance(item, dict):
            continue  # not sold (shouldn't happen) — skip
        dmg = w.get("damage")
        cd = w.get("cooldown")
        sp = w.get("speed")
        lt = w.get("lifetime")
        space = item.get("space")
        behavior = w.get("behavior") or {}
        btag = behavior.get("__tag__", "") if isinstance(behavior, dict) else ""
        carrier = btag == "CarrierBay"
        guided = btag == "Guided"
        decoy = btag == "Decoy"
        ammo = (w.get("ammo") is not None) or ("ammo_price" in item)
        licenses = item.get("required_unlocks") or []
        rng = (sp * lt) if (sp is not None and lt is not None) else None
        dps = (dmg / cd) if (dmg is not None and cd and not carrier and not decoy) else None
        dps_sp = (dps / space) if (dps is not None and space) else None
        rows.append(
            dict(
                id=wid, dmg=dmg, cd=cd, space=space, dps=dps, dps_sp=dps_sp,
                rng=rng, speed=sp, life=lt, carrier=carrier, guided=guided, decoy=decoy,
                ammo=ammo, price=item.get("price"),
                lic=", ".join(licenses) if licenses else "—",
            )
        )

    def tag(r):
        t = []
        if r["carrier"]:
            t.append("carrier-bay")
        if r["guided"]:
            t.append("guided")
        if r.get("decoy"):
            t.append("decoy")
        if r["ammo"]:
            t.append("ammo")
        return ", ".join(t) or "—"

    out = []
    out.append("# Weapons overview\n")
    out.append(
        "_Auto-generated by `scripts/weapons_overview.py` from "
        "`assets/weapons.yaml` + `assets/outfitter_items.yaml`. "
        "Re-run after changing weapon stats._\n"
    )
    out.append(
        "Derived metrics (per mounted copy; mounting N copies fires the system "
        "at rate `N/cooldown`, so it scales linearly and cancels in the "
        "per-space ratio):\n\n"
        "- **DPS** = `damage / cooldown`\n"
        "- **DPS/space** = `DPS / item-space` — damage-per-second efficiency per "
        "unit of item space\n"
        "- **Range** = `speed × lifetime` — a projectile despawns after "
        "`lifetime` seconds; guided missiles cruise at `speed`\n"
    )

    # ── DPS efficiency table ──
    out.append("\n## Damage-per-second per item-space\n")
    out.append("Best damage efficiency for the space it occupies (highest first).\n")
    out.append("\n| weapon | DPS/space | DPS | dmg | cooldown | space | type | licence |")
    out.append("|---|--:|--:|--:|--:|--:|---|---|")
    for r in sorted(
        (r for r in rows if r["dps_sp"] is not None),
        key=lambda r: r["dps_sp"], reverse=True,
    ):
        out.append(
            f"| {r['id']} | {r['dps_sp']:.2f} | {r['dps']:.2f} | {r['dmg']} | "
            f"{r['cd']:.1f} | {r['space']} | {tag(r)} | {r['lic']} |"
        )

    # ── Range table ──
    out.append("\n## Range\n")
    out.append("Straight-line reach `speed × lifetime` (highest first).\n")
    out.append("\n| weapon | range | speed | lifetime | type | licence |")
    out.append("|---|--:|--:|--:|---|---|")
    for r in sorted(
        (r for r in rows if r["rng"] is not None and not r["carrier"] and not r.get("decoy")),
        key=lambda r: r["rng"], reverse=True,
    ):
        out.append(
            f"| {r['id']} | {r['rng']:.0f} | {r['speed']:.0f} | {r['life']:.2f} | "
            f"{tag(r)} | {r['lic']} |"
        )

    out.append(
        "\n## Caveats\n"
        "- **Ammo weapons** (missiles, mines) win on *burst* DPS but their "
        "*sustained* output is capped by ammo. Among unlimited (primary) weapons "
        "the DPS/space order is what matters for a long fight.\n"
        "- **Mines** (`space_mine`, `prox_mine`) have near-zero `speed`, so their "
        "listed *range* is just how far they drift before expiring — they are "
        "area-denial dropped in place, not a firing range.\n"
        "- **Guided missiles** home, so their *effective* reach exceeds the "
        "straight-line `speed × lifetime` shown here.\n"
        "- **Turrets** trade space-efficiency for a single high-output auto-aiming "
        "mount: they rank low on DPS/space by design. If you are optimising "
        "damage-per-space, mount several small primaries instead.\n"
        "- **Carrier bays** (`*_bay`) are omitted from both tables — they launch "
        "escort ships rather than projectiles, so they have no direct DPS or "
        "projectile range; their value is the escorts they field.\n"
    )

    path = os.path.join(ROOT, "docs", "weapons_overview.md")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {path} ({len(rows)} weapons)")


if __name__ == "__main__":
    main()
