//! Runtime character-sprite compositing from LPC-derived layer sheets.
//!
//! `assets/sprites/people/layers.ron` (generated by `scripts/people_lpc_gen.py`)
//! lists layer sheets (body/head/hair/beard/torso/legs/feet/hat) in the game's
//! 18x4 layout (2 idle + 8 walk + 8 run per facing row), plus palette ramps
//! per material (body/hair/cloth/metal/eye).
//!
//! An [`AvatarSpec`] names one item per slot and one ramp per material.
//! [`CharacterLayers::composite`] stacks the layers in z-order with an
//! exact-color ramp remap into a fresh `Image`, cached by spec — so NPCs get
//! effectively infinite variety and the player can build a custom avatar.
//!
//! Convention mirrored from the generator: a hat excludes "bulky"-tagged hair.

use bevy::prelude::*;
use rand::Rng;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap};

pub const SEXES: [&str; 2] = ["male", "female"];
/// Required slots: every character has these; the rest are optional.
/// "shirt" is the base top; "over" is overwear (aprons/jackets/armour)
/// layered above it — LPC z-values stack them correctly.
pub const REQUIRED_SLOTS: [&str; 5] = ["body", "head", "shirt", "legs", "feet"];
pub const OPTIONAL_SLOTS: [&str; 4] = ["hair", "beard", "over", "hat"];

const MAX_CACHE: usize = 512;

// ── RON manifest ─────────────────────────────────────────────────────────

#[derive(Deserialize, Debug)]
struct LayersManifest {
    tile_w: u32,
    tile_h: u32,
    cols: u32,
    rows: u32,
    walk_speed: f32,
    palettes: BTreeMap<String, PaletteDef>,
    items: Vec<ItemDef>,
}

#[derive(Deserialize, Debug)]
struct PaletteDef {
    base: Vec<String>,
    ramps: BTreeMap<String, RampDef>,
}

#[derive(Deserialize, Debug)]
struct RampDef {
    group: String,
    colors: Vec<String>,
}

#[derive(Deserialize, Debug, Clone)]
struct ItemDef {
    id: String,
    slot: String,
    layer: u32,
    z: u32,
    path: String,
    /// Down-idle frame at native LPC 64px (avatar-creator preview).
    portrait: String,
    materials: Vec<String>,
    sexes: Vec<String>,
    roles: Vec<String>,
    tags: Vec<String>,
}

// ── Public data model ────────────────────────────────────────────────────

/// One color ramp (ordered light→dark or dark→light as authored).
#[derive(Clone, Debug)]
pub struct Ramp {
    pub group: String,
    pub colors: Vec<[u8; 3]>,
}

/// Palette for one material: the base ramp the art is painted in + variants.
#[derive(Clone, Debug)]
pub struct Palette {
    pub base: Vec<[u8; 3]>,
    pub ramps: BTreeMap<String, Ramp>,
}

/// A single loadable layer sheet.
#[derive(Clone, Debug)]
pub struct LayerItem {
    pub id: String,
    pub slot: String,
    pub layer: u32,
    pub z: u32,
    pub materials: Vec<String>,
    pub sexes: Vec<String>,
    pub roles: Vec<String>,
    pub tags: Vec<String>,
    pub handle: Handle<Image>,
    /// 64×64 down-idle frame (avatar-creator preview).
    pub portrait: Handle<Image>,
}

/// Everything needed to render one character. Deterministic + hashable so it
/// keys the composite cache and serializes into the pilot save.
#[derive(Serialize, Deserialize, Clone, PartialEq, Eq, Hash, Debug)]
pub struct AvatarSpec {
    /// "male" | "female"
    pub sex: String,
    /// slot -> item id (missing key = slot empty; required slots must be set)
    pub slots: BTreeMap<String, String>,
    /// material -> ramp name (missing = keep base colors)
    pub colors: BTreeMap<String, String>,
}

impl Default for AvatarSpec {
    fn default() -> Self {
        let mut slots = BTreeMap::new();
        slots.insert("body".into(), "body".into());
        slots.insert("head".into(), "head_m".into());
        slots.insert("hair".into(), "cowlick".into());
        slots.insert("shirt".into(), "tshirt".into());
        slots.insert("legs".into(), "pants".into());
        slots.insert("feet".into(), "shoes_black".into());
        let mut colors = BTreeMap::new();
        colors.insert("body".into(), "tan".into());
        colors.insert("hair".into(), "brown".into());
        colors.insert("eye".into(), "brown".into());
        colors.insert("cloth".into(), "blue".into());
        AvatarSpec { sex: "male".into(), slots, colors }
    }
}

impl AvatarSpec {
    /// Legacy boy/girl starter looks for old saves + the new-pilot default.
    pub fn for_gender(gender: crate::game_save::Gender) -> Self {
        let mut spec = Self::default();
        if matches!(gender, crate::game_save::Gender::Girl) {
            spec.sex = "female".into();
            spec.slots.insert("head".into(), "head_f".into());
            spec.slots.insert("hair".into(), "bob".into());
            spec.slots.insert("shirt".into(), "blouse_white".into());
        }
        spec
    }
}

// ── Resource ─────────────────────────────────────────────────────────────

/// Loaded layer catalog + palettes + composite cache. Inserted at startup.
#[derive(Resource)]
pub struct CharacterLayers {
    pub items: Vec<LayerItem>,
    pub palettes: BTreeMap<String, Palette>,
    pub layout: Handle<TextureAtlasLayout>,
    pub walk_speed: f32,
    pub tile: UVec2,
    cols: u32,
    rows: u32,
    cache: HashMap<AvatarSpec, Handle<Image>>,
    portrait_cache: HashMap<AvatarSpec, Handle<Image>>,
}

fn hex_rgb(s: &str) -> Option<[u8; 3]> {
    let s = s.trim_start_matches('#');
    if s.len() < 6 {
        return None;
    }
    Some([
        u8::from_str_radix(&s[0..2], 16).ok()?,
        u8::from_str_radix(&s[2..4], 16).ok()?,
        u8::from_str_radix(&s[4..6], 16).ok()?,
    ])
}

/// Parse layers.ron, kick off image loads, insert the resource.
pub fn setup_character_layers(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    mut atlas_layouts: ResMut<Assets<TextureAtlasLayout>>,
) {
    let manifest: LayersManifest = match crate::embedded_assets::read_to_string(
        "assets/sprites/people/layers.ron",
    )
    .ok()
    .and_then(|t| ron::from_str(&t).map_err(|e| eprintln!("[avatar] layers.ron: {e}")).ok())
    {
        Some(m) => m,
        None => {
            eprintln!("[avatar] WARNING: could not load layers.ron — no character compositing");
            return;
        }
    };

    let palettes = manifest
        .palettes
        .into_iter()
        .map(|(mat, p)| {
            (
                mat,
                Palette {
                    base: p.base.iter().filter_map(|c| hex_rgb(c)).collect(),
                    ramps: p
                        .ramps
                        .into_iter()
                        .map(|(name, r)| {
                            (
                                name,
                                Ramp {
                                    group: r.group,
                                    colors: r.colors.iter().filter_map(|c| hex_rgb(c)).collect(),
                                },
                            )
                        })
                        .collect(),
                },
            )
        })
        .collect();

    let items = manifest
        .items
        .into_iter()
        .map(|d| LayerItem {
            handle: asset_server.load(d.path.clone()),
            portrait: asset_server.load(d.portrait.clone()),
            id: d.id,
            slot: d.slot,
            layer: d.layer,
            z: d.z,
            materials: d.materials,
            sexes: d.sexes,
            roles: d.roles,
            tags: d.tags,
        })
        .collect();

    let layout = atlas_layouts.add(TextureAtlasLayout::from_grid(
        UVec2::new(manifest.tile_w, manifest.tile_h),
        manifest.cols,
        manifest.rows,
        None,
        None,
    ));

    commands.insert_resource(CharacterLayers {
        items,
        palettes,
        layout,
        walk_speed: manifest.walk_speed,
        tile: UVec2::new(manifest.tile_w, manifest.tile_h),
        cols: manifest.cols,
        rows: manifest.rows,
        cache: HashMap::new(),
        portrait_cache: HashMap::new(),
    });
}

impl CharacterLayers {
    /// Items usable in `slot` for `sex` (primary layer only), optionally
    /// filtered by role affinity: if any candidate carries `role`, only those
    /// are returned; otherwise role-neutral items (empty `roles`) are.
    pub fn candidates(&self, slot: &str, sex: &str, role: &str) -> Vec<&LayerItem> {
        let all: Vec<&LayerItem> = self
            .items
            .iter()
            .filter(|i| i.slot == slot && i.layer == 1 && i.sexes.iter().any(|s| s == sex))
            .collect();
        let role_specific: Vec<&LayerItem> =
            all.iter().copied().filter(|i| i.roles.iter().any(|r| r == role)).collect();
        if !role_specific.is_empty() {
            return role_specific;
        }
        all.into_iter().filter(|i| i.roles.is_empty()).collect()
    }

    /// Every item id usable in `slot` for `sex`, regardless of role — the
    /// avatar creator lets the player wear anything (chainmail included).
    pub fn all_item_ids(&self, slot: &str, sex: &str) -> Vec<String> {
        let mut ids: Vec<String> = self
            .items
            .iter()
            .filter(|i| i.slot == slot && i.layer == 1 && i.sexes.iter().any(|s| s == sex))
            .map(|i| i.id.clone())
            .collect();
        ids.sort();
        ids.dedup();
        ids
    }

    /// Ramp names of `material`, restricted to a palette group (e.g. skin
    /// "human" vs "alien"); `group: None` = all ramps.
    pub fn ramp_names(&self, material: &str, group: Option<&str>) -> Vec<&str> {
        self.palettes
            .get(material)
            .map(|p| {
                p.ramps
                    .iter()
                    .filter(|(_, r)| group.is_none_or(|g| r.group == g))
                    .map(|(n, _)| n.as_str())
                    .collect()
            })
            .unwrap_or_default()
    }

    /// Random avatar for an NPC. `role` biases outfits ("civilian", "guard",
    /// "miner", "merchant", ...); `"alien"` additionally uses alien skin tones.
    pub fn random_spec(&self, rng: &mut impl Rng, role: &str) -> AvatarSpec {
        let sex = SEXES[rng.gen_range(0..SEXES.len())].to_string();
        let mut slots = BTreeMap::new();

        for slot in REQUIRED_SLOTS {
            let cands = self.candidates(slot, &sex, role);
            if let Some(pick) = cands.get(rng.gen_range(0..cands.len().max(1))) {
                slots.insert(slot.to_string(), pick.id.clone());
            }
        }

        // Hat first: it constrains which hair fits underneath.
        let hat = if rng.gen_bool(0.15) {
            let cands = self.candidates("hat", &sex, role);
            cands.get(rng.gen_range(0..cands.len().max(1))).map(|i| i.id.clone())
        } else {
            None
        };
        if let Some(h) = &hat {
            slots.insert("hat".to_string(), h.clone());
        }
        if rng.gen_bool(0.85) {
            let mut cands = self.candidates("hair", &sex, role);
            if hat.is_some() {
                cands.retain(|i| !i.tags.iter().any(|t| t == "bulky"));
            }
            if let Some(pick) = cands.get(rng.gen_range(0..cands.len().max(1))) {
                slots.insert("hair".to_string(), pick.id.clone());
            }
        }
        if sex == "male" && rng.gen_bool(0.3) {
            let cands = self.candidates("beard", &sex, role);
            if let Some(pick) = cands.get(rng.gen_range(0..cands.len().max(1))) {
                slots.insert("beard".to_string(), pick.id.clone());
            }
        }
        // Overwear: role-specific overwear (guard armour, miner overalls,
        // merchant jackets) is the role's uniform — always worn. Civilians
        // only sometimes layer something over the shirt.
        {
            let cands = self.candidates("over", &sex, role);
            let role_specific = cands.iter().any(|i| i.roles.iter().any(|r| r == role));
            if !cands.is_empty() && (role_specific || rng.gen_bool(0.25)) {
                let pick = cands[rng.gen_range(0..cands.len())];
                slots.insert("over".to_string(), pick.id.clone());
            }
        }

        let mut colors = BTreeMap::new();
        let skin_group = if role == "alien" { "alien" } else { "human" };
        for (mat, group) in [
            ("body", Some(skin_group)),
            ("hair", None),
            ("cloth", None),
            ("metal", None),
            ("eye", None),
        ] {
            let names = self.ramp_names(mat, group);
            if !names.is_empty() {
                colors.insert(mat.to_string(), names[rng.gen_range(0..names.len())].to_string());
            }
        }

        AvatarSpec { sex, slots, colors }
    }

    /// Every layer of every item chosen by `spec` (includes behind-body
    /// layers, layer >= 2), sorted by z then layer for a stable stack.
    fn chosen_layers(&self, spec: &AvatarSpec) -> Vec<&LayerItem> {
        let mut chosen: Vec<&LayerItem> = self
            .items
            .iter()
            .filter(|i| {
                i.sexes.iter().any(|s| *s == spec.sex)
                    && spec.slots.get(&i.slot).is_some_and(|id| *id == i.id)
            })
            .collect();
        chosen.sort_by_key(|i| (i.z, i.layer, i.id.clone()));
        chosen
    }

    /// Color LUT for one layer under `spec` (exact match on base ramps).
    fn layer_lut(&self, item: &LayerItem, spec: &AvatarSpec) -> HashMap<[u8; 3], [u8; 3]> {
        let mut lut = HashMap::new();
        for mat in &item.materials {
            let (Some(pal), Some(ramp_name)) = (self.palettes.get(mat), spec.colors.get(mat))
            else {
                continue;
            };
            let Some(ramp) = pal.ramps.get(ramp_name) else { continue };
            let (nb, nt) = (pal.base.len(), ramp.colors.len());
            if nb == 0 || nt == 0 {
                continue;
            }
            // Rank-interpolate ramp lengths: j = round(i*(nt-1)/(nb-1)).
            let denom = nb.saturating_sub(1).max(1);
            for (i, src) in pal.base.iter().enumerate() {
                let j = (i * (nt - 1) + denom / 2) / denom;
                lut.insert(*src, ramp.colors[j.min(nt - 1)]);
            }
        }
        lut
    }

    /// Stack `spec`'s layers into a `w`×`h` RGBA image. `pick_handle` selects
    /// which per-item image to stack (full sheet vs 64px portrait). Returns
    /// `None` while any needed layer image is still loading.
    fn blend(
        &self,
        spec: &AvatarSpec,
        w: u32,
        h: u32,
        images: &mut Assets<Image>,
        pick_handle: impl Fn(&LayerItem) -> &Handle<Image>,
    ) -> Option<Handle<Image>> {
        let chosen = self.chosen_layers(spec);
        if chosen.is_empty() {
            return None;
        }
        let mut out = vec![0u8; (w * h * 4) as usize];

        for item in &chosen {
            let img = images.get(pick_handle(item))?;
            if img.texture_descriptor.format
                != bevy::render::render_resource::TextureFormat::Rgba8UnormSrgb
            {
                eprintln!("[avatar] {}: unexpected texture format, skipping", item.id);
                continue;
            }
            let data: &[u8] = img.data.as_ref()?;
            if data.len() != out.len() {
                eprintln!("[avatar] {}: unexpected sheet size, skipping", item.id);
                continue;
            }
            let lut = self.layer_lut(item, spec);
            // src-over composite with remap.
            for px in 0..(w * h) as usize {
                let s = &data[px * 4..px * 4 + 4];
                let sa = s[3] as u32;
                if sa == 0 {
                    continue;
                }
                let rgb = lut.get(&[s[0], s[1], s[2]]).copied().unwrap_or([s[0], s[1], s[2]]);
                let d = &mut out[px * 4..px * 4 + 4];
                if sa == 255 {
                    d[0] = rgb[0];
                    d[1] = rgb[1];
                    d[2] = rgb[2];
                    d[3] = 255;
                } else {
                    let da = d[3] as u32;
                    let oa = sa + da * (255 - sa) / 255;
                    if oa > 0 {
                        for c in 0..3 {
                            let sc = rgb[c] as u32;
                            let dc = d[c] as u32;
                            d[c] = ((sc * sa + dc * da * (255 - sa) / 255) / oa) as u8;
                        }
                    }
                    d[3] = oa as u8;
                }
            }
        }

        let mut img = Image::new(
            bevy::render::render_resource::Extent3d {
                width: w,
                height: h,
                depth_or_array_layers: 1,
            },
            bevy::render::render_resource::TextureDimension::D2,
            out,
            bevy::render::render_resource::TextureFormat::Rgba8UnormSrgb,
            bevy::asset::RenderAssetUsages::MAIN_WORLD | bevy::asset::RenderAssetUsages::RENDER_WORLD,
        );
        img.sampler = bevy::image::ImageSampler::nearest();
        Some(images.add(img))
    }

    /// Compose the full 18×4 walk sheet for `spec`. Returns `None` while any
    /// needed layer image is still loading (callers simply retry later).
    pub fn composite(
        &mut self,
        spec: &AvatarSpec,
        images: &mut Assets<Image>,
    ) -> Option<Handle<Image>> {
        if let Some(h) = self.cache.get(spec) {
            return Some(h.clone());
        }
        let (w, h) = (self.tile.x * self.cols, self.tile.y * self.rows);
        let handle = self.blend(spec, w, h, images, |item| &item.handle)?;

        if self.cache.len() >= MAX_CACHE {
            self.cache.clear();
        }
        self.cache.insert(spec.clone(), handle.clone());
        Some(handle)
    }

    /// Compose the 64×64 down-idle portrait for `spec` at native LPC
    /// resolution (used by the avatar-creator preview).
    pub fn composite_portrait(
        &mut self,
        spec: &AvatarSpec,
        images: &mut Assets<Image>,
    ) -> Option<Handle<Image>> {
        if let Some(h) = self.portrait_cache.get(spec) {
            return Some(h.clone());
        }
        let handle = self.blend(spec, 64, 64, images, |item| &item.portrait)?;

        if self.portrait_cache.len() >= MAX_CACHE {
            self.portrait_cache.clear();
        }
        self.portrait_cache.insert(spec.clone(), handle.clone());
        Some(handle)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// layers.ron (generated by scripts/people_lpc_gen.py) must stay parseable
    /// and structurally sane: required slots populated for both sexes, palette
    /// bases non-empty, every referenced material defined.
    #[test]
    fn layers_manifest_parses() {
        let text = std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/assets/sprites/people/layers.ron"
        ))
        .expect("layers.ron missing — run scripts/people_lpc_gen.py");
        let m: LayersManifest = ron::from_str(&text).expect("layers.ron failed to parse");

        assert_eq!(
            (m.tile_w, m.tile_h, m.cols as usize, m.rows),
            (32, 32, crate::surface_character::PERSON_COLS, 4)
        );
        assert!(!m.items.is_empty());
        for slot in REQUIRED_SLOTS {
            for sex in SEXES {
                assert!(
                    m.items.iter().any(|i| i.slot == slot
                        && i.layer == 1
                        && i.sexes.iter().any(|s| s == sex)),
                    "no {slot} item for {sex}"
                );
            }
        }
        for (mat, p) in &m.palettes {
            assert!(!p.base.is_empty(), "palette {mat} has empty base ramp");
            assert!(!p.ramps.is_empty(), "palette {mat} has no ramps");
        }
        for item in &m.items {
            for mat in &item.materials {
                assert!(m.palettes.contains_key(mat), "{}: unknown material {mat}", item.id);
            }
        }
        // Alien skin tones exist and are a distinct group from human ones.
        let body = &m.palettes["body"];
        assert!(body.ramps.values().any(|r| r.group == "alien"));
        assert!(body.ramps.values().any(|r| r.group == "human"));
    }
}
