//! Roaming fauna on the planet surface.
//!
//! Roamers (deer, rabbit, fox, …) wander tile-to-tile within their home
//! terrains, pause to graze, and flee when the player comes near — the mobile
//! evolution of the static `shy` peekers in `surface_objects`.  They reuse the
//! shared [`CharacterAnim`]/[`Facing`] directional walk animation (driven by
//! `LinearVelocity`), so this module only owns the AI: spawn/maintain a small
//! off-screen-respawning population, and the graze/wander/flee state machine.
//!
//! Art + per-species data come from `assets/sprites/fauna/fauna_manifest.ron`
//! (generated by `scripts/ship3d/fauna3d.py`).

use avian2d::prelude::*;
use bevy::prelude::*;
use rand::{Rng, SeedableRng};
use serde::Deserialize;

use crate::PlayState;
use crate::surface::{TILE_PX, Walker};
use crate::surface_character::CharacterAnim;
use crate::surface_objects::depth_z;
use crate::surface_pathfinding::SurfaceCostMap;

// ── Tuning ────────────────────────────────────────────────────────────────

/// How many roamers to keep alive on the surface at once.
const TARGET_FAUNA_COUNT: usize = 6;
/// Player distance (px) at which a roamer panics and flees.
const FLEE_RADIUS: f32 = 130.0;
/// Once this far from the player, a fleeing roamer calms and resumes grazing.
const CALM_DIST: f32 = 300.0;
/// Roamers this far from the player despawn (recycled off-screen).
const DESPAWN_DIST: f32 = 1500.0;
/// New roamers spawn this far from the player (off-screen) … but no further.
const SPAWN_MIN_DIST: f32 = 520.0;
const SPAWN_MAX_DIST: f32 = 1250.0;
/// Wander target is within this many tiles of the current position.
const WANDER_TILES: i32 = 5;
/// World distance (px) below which a roamer counts as "arrived" at its target.
const ARRIVE_DIST: f32 = 5.0;
/// Fliers float this many px above their ground track and sort over everything.
const FLY_ALTITUDE: f32 = 64.0;
const FLY_Z: f32 = 8.0;
/// Flier drift hop length (px).
const FLY_DRIFT_MIN: f32 = 70.0;
const FLY_DRIFT_MAX: f32 = 220.0;
/// Herd species bias their wander search this fraction of the way toward the
/// flock centroid, so they regroup and drift together (0 = none, 1 = at centroid).
const HERD_BIAS: f32 = 0.5;

// ── RON manifest ─────────────────────────────────────────────────────────

#[derive(Deserialize, Debug)]
struct FaunaManifest {
    species: Vec<FaunaSpeciesDef>,
}

#[derive(Deserialize, Debug)]
struct FaunaSpeciesDef {
    #[allow(dead_code)] // kept for manifest readability / debugging
    name: String,
    sheet: String,
    biome: String,
    terrains: Vec<String>,
    tile_w: u32,
    tile_h: u32,
    speed: f32,
    flee_speed: f32,
    group: u32,
    flier: bool,
}

// ── Resources ──────────────────────────────────────────────────────────────

/// A spawnable species resolved for the current surface's biome.
struct FaunaSpecies {
    image: Handle<Image>,
    layout: Handle<TextureAtlasLayout>,
    /// Home-terrain indices into the current biome's terrain table.
    terrain_idxs: Vec<u32>,
    speed: f32,
    flee_speed: f32,
    group: u32,
    foot_off: f32,
    flier: bool,
}

/// Loaded fauna data + the live terrain grid, for the spawn/AI systems.
/// Only the species matching the surface's biome are kept.
#[derive(Resource)]
pub struct FaunaWorld {
    species: Vec<FaunaSpecies>,
    terrain: Vec<u32>,
    map_w: u32,
    map_h: u32,
    rng: rand::rngs::StdRng,
    spawn_timer: Timer,
    /// Which on-foot state owns the critters (surface or interior).
    scope: PlayState,
}

/// Is tile (tx, ty) a valid home tile for the given terrain set? (Free fn so
/// callers can split-borrow `FaunaWorld`'s rng and grid fields independently.)
fn tile_ok(terrain: &[u32], map_w: u32, map_h: u32, idxs: &[u32], tx: i32, ty: i32) -> bool {
    if tx < 0 || ty < 0 || tx as u32 >= map_w || ty as u32 >= map_h {
        return false;
    }
    idxs.contains(&terrain[(ty as u32 * map_w + tx as u32) as usize])
}

// ── Component ──────────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq)]
enum FaunaState {
    Graze,
    Wander,
    Flee,
}

#[derive(Component)]
pub struct Fauna {
    species: usize,
    speed: f32,
    flee_speed: f32,
    foot_off: f32,
    state: FaunaState,
    timer: Timer,
    target: Vec2,
    flier: bool,
}

// ── Setup / teardown (called from surface.rs) ───────────────────────────────

/// Load the fauna manifest, resolve the species that belong to `biome_name`,
/// and insert [`FaunaWorld`].  Call from `setup_surface`.
#[allow(clippy::too_many_arguments)]
#[allow(clippy::too_many_arguments)]
pub fn setup_fauna(
    commands: &mut Commands,
    asset_server: &AssetServer,
    atlas_layouts: &mut Assets<TextureAtlasLayout>,
    terrain_flat: &[u32],
    terrain_names: &[String],
    biome_name: &str,
    map_w: u32,
    map_h: u32,
    seed: u64,
    scope: PlayState,
) {
    let manifest: FaunaManifest =
        match crate::embedded_assets::read_to_string("assets/sprites/fauna/fauna_manifest.ron")
            .ok()
            .and_then(|t| ron::from_str(&t).ok())
        {
            Some(m) => m,
            None => {
                eprintln!("[fauna] WARNING: could not load fauna_manifest.ron");
                return;
            }
        };

    let idx_by_name: std::collections::HashMap<&str, u32> = terrain_names
        .iter()
        .enumerate()
        .map(|(i, n)| (n.as_str(), i as u32))
        .collect();

    let mut species = Vec::new();
    for def in &manifest.species {
        if def.biome != biome_name {
            continue;
        }
        let terrain_idxs: Vec<u32> = def
            .terrains
            .iter()
            .filter_map(|t| idx_by_name.get(t.as_str()).copied())
            .collect();
        if terrain_idxs.is_empty() {
            continue;
        }
        let layout = atlas_layouts.add(TextureAtlasLayout::from_grid(
            UVec2::new(def.tile_w, def.tile_h),
            3, // still, w1, w2
            4, // down, left, right, up
            None,
            None,
        ));
        species.push(FaunaSpecies {
            image: asset_server.load(def.sheet.clone()),
            layout,
            terrain_idxs,
            speed: def.speed,
            flee_speed: def.flee_speed,
            group: def.group.max(1),
            foot_off: def.tile_h as f32 * 0.35,
            flier: def.flier,
        });
    }

    if species.is_empty() {
        return; // this biome has no roamers yet
    }

    commands.insert_resource(FaunaWorld {
        species,
        terrain: terrain_flat.to_vec(),
        map_w,
        map_h,
        rng: rand::rngs::StdRng::seed_from_u64(seed.wrapping_add(0xFA00_0001)),
        spawn_timer: Timer::from_seconds(1.5, TimerMode::Repeating),
        scope,
    });
}

pub fn cleanup_fauna(mut commands: Commands) {
    commands.remove_resource::<FaunaWorld>();
}

// ── Spawn / maintain population ──────────────────────────────────────────────

pub fn spawn_fauna(
    mut commands: Commands,
    world: Option<ResMut<FaunaWorld>>,
    time: Res<Time>,
    walker: Query<&Transform, With<Walker>>,
    existing: Query<(), With<Fauna>>,
) {
    let Some(mut world) = world else { return };
    world.spawn_timer.tick(time.delta());
    if !world.spawn_timer.just_finished() {
        return;
    }
    if existing.iter().count() >= TARGET_FAUNA_COUNT {
        return;
    }
    let Ok(player) = walker.single() else { return };
    let ppos = player.translation.truncate();
    let world = &mut *world; // reborrow for disjoint field access (rng vs grid)

    // Pick a species, then a valid home tile off-screen from the player.
    let sp_idx = world.rng.r#gen_range(0..world.species.len());
    let (map_w, map_h) = (world.map_w, world.map_h);
    let mut anchor = None;
    for _ in 0..40 {
        let tx = world.rng.r#gen_range(0..map_w) as i32;
        let ty = world.rng.r#gen_range(0..map_h) as i32;
        if !tile_ok(
            &world.terrain,
            map_w,
            map_h,
            &world.species[sp_idx].terrain_idxs,
            tx,
            ty,
        ) {
            continue;
        }
        let wp = SurfaceCostMap::tile_to_world(tx as u32, ty as u32);
        let d = wp.distance(ppos);
        if (SPAWN_MIN_DIST..SPAWN_MAX_DIST).contains(&d) {
            anchor = Some((tx, ty));
            break;
        }
    }
    let Some((ax, ay)) = anchor else { return };

    // Herd species spawn a small cluster around the anchor.
    let group = world.species[sp_idx].group;
    for i in 0..group {
        let (tx, ty) = if i == 0 {
            (ax, ay)
        } else {
            let mut found = (ax, ay);
            for _ in 0..8 {
                let cx = ax + world.rng.r#gen_range(-2..=2);
                let cy = ay + world.rng.r#gen_range(-2..=2);
                if tile_ok(
                    &world.terrain,
                    map_w,
                    map_h,
                    &world.species[sp_idx].terrain_idxs,
                    cx,
                    cy,
                ) {
                    found = (cx, cy);
                    break;
                }
            }
            found
        };
        let ground = SurfaceCostMap::tile_to_world(tx as u32, ty as u32);
        let sp = &world.species[sp_idx];
        let flier = sp.flier;
        let graze = world.rng.r#gen_range(1.2..3.5);
        // Fliers float above their ground track and sort over everything.
        let pos = if flier {
            Vec2::new(ground.x, ground.y + FLY_ALTITUDE)
        } else {
            ground
        };
        let z = if flier {
            FLY_Z
        } else {
            depth_z(pos.y - sp.foot_off)
        };
        let scope = world.scope.clone();
        let mut ent = commands.spawn((
            DespawnOnExit(scope.clone()),
            Fauna {
                species: sp_idx,
                speed: sp.speed,
                flee_speed: sp.flee_speed,
                foot_off: sp.foot_off,
                flier,
                state: if flier {
                    FaunaState::Wander
                } else {
                    FaunaState::Graze
                },
                timer: Timer::from_seconds(graze, TimerMode::Once),
                target: pos,
            },
            CharacterAnim::legacy_rpg(if flier { 0.11 } else { 0.16 }),
            RigidBody::Dynamic,
            LockedAxes::ROTATION_LOCKED,
            LinearDamping(if flier { 4.0 } else { 12.0 }),
            LinearVelocity(Vec2::ZERO),
            Sprite::from_atlas_image(
                sp.image.clone(),
                TextureAtlas {
                    layout: sp.layout.clone(),
                    index: 0,
                },
            ),
            Transform::from_xyz(pos.x, pos.y, z),
        ));
        // Roamers collide with the terrain; fliers pass over everything but still
        // need explicit mass (a dynamic body with no collider is mass-less → avian
        // "no mass or inertia" NaN warning).
        if !flier {
            if scope == PlayState::Inside {
                ent.insert(crate::surface::interiors::InteriorScoped);
            }
            ent.insert((
                Collider::circle(4.0),
                CollisionLayers::new(crate::GameLayer::Character, [crate::GameLayer::Surface]),
            ));
        } else {
            ent.insert(MassPropertiesBundle::from_shape(
                &Collider::circle(4.0),
                0.5,
            ));
        }
    }
}

// ── Behaviour: graze ↔ wander ↔ flee ─────────────────────────────────────────

pub fn run_fauna(
    mut commands: Commands,
    time: Res<Time>,
    world: Option<ResMut<FaunaWorld>>,
    walker: Query<&Transform, With<Walker>>,
    mut q: Query<(Entity, &mut Fauna, &Transform, &mut LinearVelocity), Without<Walker>>,
) {
    let Some(mut world) = world else { return };
    let world = &mut *world; // reborrow for disjoint field access (rng vs grid)
    let ppos = walker.single().ok().map(|t| t.translation.truncate());

    // Per-species herd centroid (read-only pass) so group roamers drift together.
    let mut sums: std::collections::HashMap<usize, (Vec2, f32)> = std::collections::HashMap::new();
    for (_, fauna, tf, _) in q.iter() {
        if !fauna.flier {
            let e = sums.entry(fauna.species).or_insert((Vec2::ZERO, 0.0));
            e.0 += tf.translation.truncate();
            e.1 += 1.0;
        }
    }
    let centroids: std::collections::HashMap<usize, Vec2> =
        sums.iter().map(|(k, (s, n))| (*k, *s / *n)).collect();

    for (entity, mut fauna, tf, mut vel) in &mut q {
        let pos = tf.translation.truncate();

        // Recycle anything that has drifted far off-screen.
        if let Some(pp) = ppos
            && pos.distance(pp) > DESPAWN_DIST
        {
            commands.entity(entity).despawn();
            continue;
        }

        // Fliers drift over the map ignoring terrain, never fleeing — so they
        // stay above MOVE_THRESHOLD and keep flapping.
        if fauna.flier {
            if (fauna.target - pos).length() < ARRIVE_DIST {
                let ang = world.rng.r#gen_range(0.0..std::f32::consts::TAU);
                let r = world.rng.r#gen_range(FLY_DRIFT_MIN..FLY_DRIFT_MAX);
                let hw = world.map_w as f32 * TILE_PX * 0.5 - TILE_PX;
                let hh = world.map_h as f32 * TILE_PX * 0.5 - TILE_PX;
                let t = pos + Vec2::from_angle(ang) * r;
                fauna.target = Vec2::new(
                    t.x.clamp(-hw, hw),
                    t.y.clamp(-hh + FLY_ALTITUDE, hh + FLY_ALTITUDE),
                );
            }
            vel.0 = (fauna.target - pos).normalize_or_zero() * fauna.speed;
            continue;
        }

        // Roamers panic when the player is close.
        if let Some(pp) = ppos
            && pos.distance(pp) < FLEE_RADIUS
            && fauna.state != FaunaState::Flee
        {
            fauna.state = FaunaState::Flee;
        }

        match fauna.state {
            FaunaState::Flee => {
                let away = ppos
                    .map(|pp| (pos - pp).normalize_or_zero())
                    .filter(|v| *v != Vec2::ZERO)
                    .unwrap_or(Vec2::Y);
                vel.0 = away * fauna.flee_speed;
                let calm = ppos.map(|pp| pos.distance(pp) > CALM_DIST).unwrap_or(true);
                if calm {
                    fauna.state = FaunaState::Graze;
                    fauna.timer =
                        Timer::from_seconds(world.rng.r#gen_range(1.2..3.0), TimerMode::Once);
                }
            }
            FaunaState::Graze => {
                vel.0 = Vec2::ZERO;
                fauna.timer.tick(time.delta());
                if fauna.timer.just_finished() {
                    // Pick a nearby valid home tile to wander to.
                    let (map_w, map_h) = (world.map_w, world.map_h);
                    let sp_ref = &world.species[fauna.species];
                    let idxs = &sp_ref.terrain_idxs;
                    let group = sp_ref.group;
                    // Herd species bias the search toward the flock centroid.
                    let (cx, cy) = tile_of(pos);
                    let (cx, cy) = match centroids.get(&fauna.species) {
                        Some(cen) if group > 1 => {
                            let (ctx, cty) = tile_of(*cen);
                            (
                                cx + ((ctx - cx) as f32 * HERD_BIAS).round() as i32,
                                cy + ((cty - cy) as f32 * HERD_BIAS).round() as i32,
                            )
                        }
                        _ => (cx, cy),
                    };
                    let mut picked = None;
                    for _ in 0..16 {
                        let nx = cx + world.rng.r#gen_range(-WANDER_TILES..=WANDER_TILES);
                        let ny = cy + world.rng.r#gen_range(-WANDER_TILES..=WANDER_TILES);
                        if tile_ok(&world.terrain, map_w, map_h, idxs, nx, ny) {
                            picked = Some(SurfaceCostMap::tile_to_world(nx as u32, ny as u32));
                            break;
                        }
                    }
                    if let Some(t) = picked {
                        fauna.target = t;
                        fauna.state = FaunaState::Wander;
                    } else {
                        fauna.timer = Timer::from_seconds(1.5, TimerMode::Once);
                    }
                }
            }
            FaunaState::Wander => {
                let to = fauna.target - pos;
                if to.length() < ARRIVE_DIST {
                    fauna.state = FaunaState::Graze;
                    fauna.timer =
                        Timer::from_seconds(world.rng.r#gen_range(1.5..4.0), TimerMode::Once);
                    vel.0 = Vec2::ZERO;
                } else {
                    vel.0 = to.normalize_or_zero() * fauna.speed;
                }
            }
        }
    }
}

/// Depth-sort fauna each frame: roamers y-sort with the ground (feet below
/// sprite centre); fliers sort at a fixed high z, over ground and player.
pub fn depth_sort_fauna(mut q: Query<(&mut Transform, &Fauna)>) {
    for (mut tf, fauna) in &mut q {
        tf.translation.z = if fauna.flier {
            FLY_Z
        } else {
            depth_z(tf.translation.y - fauna.foot_off)
        };
    }
}

fn tile_of(pos: Vec2) -> (i32, i32) {
    let (tx, ty) = SurfaceCostMap::world_to_tile(pos);
    (tx as i32, ty as i32)
}
