//! Landscape object spawning and animation for the planet surface.
//!
//! Objects are loaded from `objects_manifest.ron` (generated by
//! `scripts/objects.py`) and placed via Poisson-disk sampling on
//! walkable terrain tiles.  Each object has animated frames and
//! depth-sorted rendering based on its y-position.

use bevy::prelude::*;
use rand::{Rng, SeedableRng};
use serde::Deserialize;
use std::collections::HashMap;

use crate::PlayState;
use crate::surface::{TILE_PX, Walker};

// ── Constants ────────────────────────────────────────────────────────────

const WORLDS_DIR: &str = "sprites/worlds";

/// Z-base for depth-sorted surface entities (above tilemap at -10).
pub const DEPTH_Z_BASE: f32 = -4.0;

/// World-Y units per z unit. Large = gentle sort across the full map range.
pub const DEPTH_Z_SCALE: f32 = 10000.0;

/// Compute the z value for depth sorting on the surface.
/// `foot_y` is the world-y of the entity's visual bottom (feet / base).
/// Entities with larger foot_y (lower on screen in bevy's +Y-up) get
/// smaller z and therefore render in front.
#[inline]
pub fn depth_z(foot_y: f32) -> f32 {
    DEPTH_Z_BASE - foot_y / DEPTH_Z_SCALE
}

// ── RON types ────────────────────────────────────────────────────────────

#[derive(Deserialize, Debug)]
struct ObjectDef {
    name: String,
    /// Pixel y-offset of this object's region in the combined atlas.
    y_px: u32,
    n_frames: u32,
    n_variants: u32,
    tile_w: u32,
    tile_h: u32,
    terrains: Vec<String>,
    density: f32,
    min_distance: f32,
    max_per_tile: u32,
    y_offset: f32,
    shy: bool,
}

#[derive(Deserialize, Debug)]
struct BiomeObjectsDef {
    atlas: String,
    objects: Vec<ObjectDef>,
}

#[derive(Deserialize, Debug)]
struct ObjectsManifest {
    tile_size: u32,
    biomes: HashMap<String, BiomeObjectsDef>,
}

// ── Components ───────────────────────────────────────────────────────────

/// Marker for all landscape object sprites.
#[derive(Component)]
pub struct LandscapeObject;

/// Shy objects hide (reset to frame 0) when the walker is nearby.
#[derive(Component)]
pub struct ShyObject {
    /// Squared distance threshold for hiding.
    pub hide_radius_sq: f32,
}

/// Animation state for an animated landscape object.
#[derive(Component)]
pub struct ObjectAnim {
    /// Atlas index for frame 0 of this object's variant.
    base_index: usize,
    n_frames: u32,
    /// Stride between frames in the flat atlas index (= n_variants).
    frame_stride: usize,
    timer: Timer,
    current_frame: u32,
}

// ── Public API ───────────────────────────────────────────────────────────

/// Call from `setup_surface` to spawn landscape objects.
///
/// * `terrain_flat` — flat terrain index array (bottom-up, row-major)
/// * `terrain_names` — terrain name per index (from the world manifest)
/// * `biome_name` — which biome to look up in the objects manifest
/// * `map_w`, `map_h` — terrain map dimensions
/// * `seed` — planet seed for deterministic placement
/// * `building_rects` — `(x, y, w, h)` rectangles to avoid
pub fn spawn_landscape_objects(
    commands: &mut Commands,
    asset_server: &AssetServer,
    atlas_layouts: &mut Assets<TextureAtlasLayout>,
    terrain_flat: &[u32],
    terrain_names: &[String],
    biome_name: &str,
    map_w: u32,
    map_h: u32,
    seed: u64,
    building_rects: &[(u32, u32, u32, u32)],
) {
    // Load manifest synchronously.
    let manifest: ObjectsManifest = match crate::embedded_assets::read_to_string(
        &format!("assets/{WORLDS_DIR}/objects_manifest.ron"),
    )
    .ok()
    .and_then(|t| ron::from_str(&t).ok())
    {
        Some(m) => m,
        None => {
            eprintln!("[surface_objects] WARNING: could not load objects_manifest.ron");
            return;
        }
    };

    let biome_def = match manifest.biomes.get(biome_name) {
        Some(b) => b,
        None => return,
    };

    let atlas_handle: Handle<Image> =
        asset_server.load(format!("{WORLDS_DIR}/{}", biome_def.atlas));

    // Build terrain name → index lookup.
    let terrain_idx_by_name: HashMap<&str, u32> = terrain_names
        .iter()
        .enumerate()
        .map(|(i, n)| (n.as_str(), i as u32))
        .collect();

    let tile_px = TILE_PX;
    let mut rng = rand::rngs::StdRng::seed_from_u64(seed.wrapping_add(0xDEAD_BEEF));

    // Generate a density fBm field for modulating spawn probability.
    let density_field = crate::fbm::generate_terrain_map(
        map_w, map_h, 10, // 10 bins for fine-grained density
        3.0, 3, 2.0, 0.5,
        seed.wrapping_add(777),
    );

    // Track placed object positions for Poisson-disk min_distance.
    // Key: object name, Value: list of (world_x, world_y).
    let mut placed: HashMap<String, Vec<(f32, f32)>> = HashMap::new();

    for obj_def in &biome_def.objects {
        // Which terrain indices does this object appear on?
        let valid_terrains: Vec<u32> = obj_def
            .terrains
            .iter()
            .filter_map(|tn| terrain_idx_by_name.get(tn.as_str()).copied())
            .collect();
        if valid_terrains.is_empty() {
            continue;
        }

        // Build a per-object atlas layout using custom rects.
        // Each sprite is at (variant * tile_w, y_px + frame * tile_h).
        let mut obj_layout = TextureAtlasLayout::new_empty(UVec2::new(
            obj_def.n_variants * obj_def.tile_w,
            // Atlas total height doesn't matter for rect-based layouts,
            // but we need a reasonable value.
            biome_def.objects.iter().map(|o| o.n_frames * o.tile_h).sum(),
        ));
        for frame in 0..obj_def.n_frames {
            for var in 0..obj_def.n_variants {
                obj_layout.add_texture(URect::new(
                    var * obj_def.tile_w,
                    obj_def.y_px + frame * obj_def.tile_h,
                    (var + 1) * obj_def.tile_w,
                    obj_def.y_px + (frame + 1) * obj_def.tile_h,
                ));
            }
        }
        let layout = atlas_layouts.add(obj_layout);

        let positions = placed.entry(obj_def.name.clone()).or_default();

        for y in 0..map_h {
            for x in 0..map_w {
                let idx = (y * map_w + x) as usize;
                let terrain = terrain_flat[idx];

                if !valid_terrains.contains(&terrain) {
                    continue;
                }

                // Skip building footprints.
                let in_building = building_rects.iter().any(|&(bx, by, bw, bh)| {
                    x >= bx && x < bx + bw && y >= by && y < by + bh
                });
                if in_building {
                    continue;
                }

                // Density modulation: base density × fBm density field (0.0–1.0).
                let density_val = density_field[idx] as f32 / 9.0;
                let spawn_prob = obj_def.density * density_val;

                // How many to spawn on this tile.
                let count = (0..obj_def.max_per_tile)
                    .filter(|_| rng.r#gen::<f32>() < spawn_prob)
                    .count();

                for _ in 0..count {
                    // Jitter within the tile.
                    let jx = rng.r#gen_range(-0.4..0.4) * tile_px;
                    let jy = rng.r#gen_range(-0.4..0.4) * tile_px;

                    let world_x = (x as f32 - map_w as f32 / 2.0) * tile_px
                        + tile_px / 2.0
                        + jx;
                    let world_y = (y as f32 - map_h as f32 / 2.0) * tile_px
                        + tile_px / 2.0
                        + jy;

                    // Poisson-disk distance check.
                    let min_d_sq = obj_def.min_distance * obj_def.min_distance;
                    let too_close = positions
                        .iter()
                        .any(|&(px, py)| {
                            (world_x - px).powi(2) + (world_y - py).powi(2) < min_d_sq
                        });
                    if too_close {
                        continue;
                    }
                    positions.push((world_x, world_y));

                    // Pick random variant and starting frame.
                    let variant = rng.r#gen_range(0..obj_def.n_variants);
                    let start_frame = rng.r#gen_range(0..obj_def.n_frames);

                    // Index into the per-object layout: frame * n_variants + variant.
                    let atlas_index = start_frame * obj_def.n_variants + variant;

                    // Depth sort: y_offset shifts the sort anchor to the
                    // object's visual base (feet / bottom pixel).
                    // Positive y_offset = base is below sprite center.
                    let foot_y = world_y - obj_def.y_offset;
                    let z = depth_z(foot_y);

                    let mut entity = commands.spawn((
                        DespawnOnExit(PlayState::Exploring),
                        LandscapeObject,
                        Sprite::from_atlas_image(
                            atlas_handle.clone(),
                            TextureAtlas {
                                layout: layout.clone(),
                                index: atlas_index as usize,
                            },
                        ),
                        Transform::from_xyz(world_x, world_y, z),
                    ));

                    // Add animation if more than 1 frame.
                    if obj_def.n_frames > 1 {
                        // Randomize timer phase so objects aren't synchronized.
                        let phase = rng.r#gen_range(0.0..0.3);
                        let mut timer = Timer::from_seconds(0.25 + phase, TimerMode::Repeating);
                        timer.tick(std::time::Duration::from_secs_f32(
                            rng.r#gen_range(0.0..0.25 + phase),
                        ));

                        entity.insert(ObjectAnim {
                            base_index: variant as usize, // frame 0 of this variant
                            n_frames: obj_def.n_frames,
                            frame_stride: obj_def.n_variants as usize,
                            timer,
                            current_frame: start_frame,
                        });
                    }

                    // Shy objects hide when the walker gets close.
                    if obj_def.shy {
                        let hide_radius = tile_px * 1.5;
                        entity.insert(ShyObject {
                            hide_radius_sq: hide_radius * hide_radius,
                        });
                    }
                }
            }
        }
    }
}

// ── Animation system ─────────────────────────────────────────────────────

/// Update the walker's z for depth sorting (every frame).
pub fn depth_sort_walker(
    mut walkers: Query<&mut Transform, With<Walker>>,
) {
    let Ok(mut tf) = walkers.single_mut() else { return };
    // Walker sprite is 16px tall, centered — feet are 8px below center.
    let foot_y = tf.translation.y - 8.0;
    tf.translation.z = depth_z(foot_y);
}

/// Shy objects reset to frame 0 (hidden) when the walker is nearby.
pub fn update_shy_objects(
    walker_q: Query<&Transform, With<Walker>>,
    mut shy_q: Query<(&Transform, &ShyObject, &mut ObjectAnim, &mut Sprite), Without<Walker>>,
) {
    let Ok(walker_tf) = walker_q.single() else { return };
    let wp = walker_tf.translation.truncate();

    for (tf, shy, mut anim, mut sprite) in &mut shy_q {
        let pos = tf.translation.truncate();
        let dist_sq = (wp - pos).length_squared();

        if dist_sq < shy.hide_radius_sq {
            // Walker is close — snap to frame 0 (hidden).
            if anim.current_frame != 0 {
                anim.current_frame = 0;
                anim.timer.reset();
                if let Some(atlas) = &mut sprite.texture_atlas {
                    atlas.index = anim.base_index;
                }
            }
            // Pause the timer so it doesn't advance while hiding.
            anim.timer.pause();
        } else {
            // Walker is far — let animation run.
            anim.timer.unpause();
        }
    }
}

/// Advance animated landscape objects.
pub fn animate_landscape_objects(
    time: Res<Time>,
    mut query: Query<(&mut ObjectAnim, &mut Sprite), With<LandscapeObject>>,
) {
    for (mut anim, mut sprite) in &mut query {
        anim.timer.tick(time.delta());
        if anim.timer.just_finished() {
            anim.current_frame = (anim.current_frame + 1) % anim.n_frames;
            if let Some(atlas) = &mut sprite.texture_atlas {
                atlas.index = anim.base_index + anim.current_frame as usize * anim.frame_stride;
            }
        }
    }
}
